@baseUrl=http://localhost:8081

@subjectCode=1053486524-B
@careerId=1
@subjectName=Physics
@subjectId=1

@groupId=cca4c365-befb-4d4b-bd42-d9b92384a57d

### ---- Subjects ----

### Get all subjects
# @name getSubjects
GET {{baseUrl}}/subjects HTTP/1.1

### Get subject by carrer id
# @name getSubjectByCareerId
GET {{baseUrl}}/subjects?careerId={{careerId}} HTTP/1.1

### Get subject by subject code
# @name getSubjectBySubjectCode
GET {{baseUrl}}/subjects?subjectCode={{subjectCode}} HTTP/1.1

### Get subject by subject_name
# @name getSubjectBySubjectName
GET {{baseUrl}}/subjects?subjectName={{subjectName}} HTTP/1.1

### Get subject by subject id
# @name getSubjectBySubjectId
GET {{baseUrl}}/subjects/{{subjectId}} HTTP/1.1


### ---- Class Groups ----

### Get all class groups
# @name getClassGroups
GET {{baseUrl}}/groups HTTP/1.1

### Get group by id
# @name getGroupById
GET {{baseUrl}}/groups/{{groupId}} HTTP/1.1
