@baseUrl=http://localhost:8081

@subjectCode=1053486524-B
@subjectName=Physics
@careerId=1

@groupId=cca4c365-befb-4d4b-bd42-d9b92384a57d


### Get subjects by code
# @name get_subject_by_code
GET {{baseUrl}}/subjects?code={{subjectCode}} HTTP/1.1

### Get subjects by name
# @name get_subject_by_name
GET {{baseUrl}}/subjects?name={{subjectName}} HTTP/1.1

### Get subject by carrer_id
# @name get_subject_by_career_id
GET {{baseUrl}}/subjects?career={{careerId}} HTTP/1.1



### ---- Class Groups ----

### Get group by id
# @name get_group_by_id
GET {{baseUrl}}/group/{{groupId}} HTTP/1.1